@startuml
'https://plantuml.com/class-diagram


Player"n"<-->"1"Lobby

PlayerCardPackages *- ChampCard : have 5 >
Player"1"<-->"n"PlayerCardPackages
PlayerCardPackages *- ItemCard : have 5 >



class ItemCard {
-Integer: ItemCardID
-String:  ItemName
-Integer: ItemDamage
-Integer: ItemDefence
-Integer:ItemCardPrice
}

class ChampCard {
-Integer: CampCardID
-String:  CampName
-Integer: CampDamage
-Integer: CampDefence
-Integer: CampCardPrice
}


class Lobby {
-Integer: PlayerID
-String: PlayerName
-Integer: PlayerElo
}
class GameRoom {
-Integer: RoomID
-Integer: NumberOfPlayer
-Integer: PlayerID
-String: PlayerName
-Integer:PlayerCoin
-Integer: PlayerElo
}

class Player{
-Integer: PlayerID
-String: Password
-String: PlayerName
-Integer: PlayerCoin
-Integer: PlayerElo
-Integer: CardPackageID
}

class PlayerCardPackages{
-Integer: CardPackageID
-String: CardPackageName
-Integer: CardPackagePrice
-Integer: TotalDefence
-Integer: TotalPower
-Integer: FirstCampCardID
-Integer: SecondCampCardID
-Integer: ThirdCampCardID
-Integer: FourthCampCardID
-Integer: FifthCampCardID
-Integer: FirstItemCardID
-Integer: SecondItemCardID
-Integer: ThirdItemCardID
-Integer: FourthItemCardID
-Integer: FifthItemCardID

}


@enduml